spring:
  application:
    name: library-user-service
  datasource:
    url: jdbc:postgresql://${DATABASE_URL}/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
  cloud:
    stream:
      bindings:
        on-user-registration-notification-out-0:
          destination: user-registration-notification
          content-type: application/json
      kafka:
        binder:
          brokers: localhost:9092
          auto-create-topics: true
paths:
  books: ${BOOKS_PATH}