/*
 * Library service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.vitalii.fedyk.libraryuserservice.dto;

import java.util.Objects;
import java.util.Arrays;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Genre of the book
 */
public enum BookGenreDto {
  
  FICTION("FICTION"),
  
  NON_FICTION("NON_FICTION"),
  
  SCIENCE_FICTION("SCIENCE_FICTION"),
  
  FANTASY("FANTASY"),
  
  MYSTERY("MYSTERY"),
  
  BIOGRAPHY("BIOGRAPHY"),
  
  HISTORICAL("HISTORICAL"),
  
  ROMANCE("ROMANCE"),
  
  THRILLER("THRILLER"),
  
  HORROR("HORROR"),
  
  SELF_HELP("SELF_HELP"),
  
  HEALTH("HEALTH"),
  
  COOKBOOK("COOKBOOK"),
  
  CHILDREN("CHILDREN");

  private String value;

  BookGenreDto(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static BookGenreDto fromValue(String value) {
    for (BookGenreDto b : BookGenreDto.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}

